---
title: Fight With Tools by AramZS
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: aramzs@hacktext.com
description: 'A site discussing how to imagine, build, analyze and use cool code and
  web tools. Better websites, better stories, better developers. Technology won''t
  save the world, but you can.

'
baseurl: 
url: http://aramzs.github.io
twitter_username: Chronotope
github_username: aramzs
glitch_in_bio: aramzs
markdown: kramdown
plugins:
- jekyll-toc
