# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fight With Tools by AramZS
email: aramzs@hacktext.com
description: > # this means to ignore newlines until "baseurl:"
  A site discussing how to imagine, build, analyze and use cool code and
  web tools. Better websites, better stories, better developers. Technology
  won't save the world, but you can.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aramzs.github.io" # the base hostname & protocol for your site
twitter_username: Chronotope
github_username:  aramzs

# Build settings
markdown: kramdown
